Added Russian language
denysdovhan/purifier-card pull request #42
Opened 2021-03-18 18:32 UTC by eksploit

2021-03-22 13:22 UTC, denysdovhan requested changes
Please, read contribution guide: https://github.com/denysdovhan/purifier-card/blob/master/CONTRIBUTING.md#how-to-add-translation

You must include your translation in `src/localize.js`

2021-03-22 18:43 UTC, eksploit commented
> 
> 
> Please, read contribution guide: https://github.com/denysdovhan/purifier-card/blob/master/CONTRIBUTING.md#how-to-add-translation
> 
> You must include your translation in `src/localize.js`

Sorry, did not notice, fixed

2021-03-25 13:35 UTC, denysdovhan requested changes

2021-03-25 13:35 UTC, denysdovhan commented on src/localize.js
> +import * as ca from './translations/ru.json';
```suggestion
import * as ru from './translations/ru.json';
```

2021-04-19 12:26 UTC, denysdovhan approved these changes

2021-04-19 12:27 UTC, merged

2021-04-19 12:27 UTC, denysdovhan commented
Thanks for contributing!